### ISSUE TITLE
Error: "unable to find an inherited method for function"

### ISSUE THREAD

**Issue by pedro-mmartins** [nthomasCUBE/traitCorr#2]
Hello! How are you doing?

I tried to run traitCorr, but I've had some problems.

When I run `source("run_traitCorr.R")`, this message comes up: `Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘print’ for signature ‘"character"’`, and I can't even choose an input file.

If I run:
`source("methods.R")`
`source("ui.R")`
`source("server.R")`
`shinyApp(ui,server)`
The pop up appears, but as soon as I choose an input file, the following message comes up: `Listening on http://127.0.0.1:3355
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘print’ for signature ‘"character"’
  [No stack trace available]`

Finally, if do as mentioned in the second example, but chose the option of running it on my browser, I can choose an input file, but just one. After I choose it, the screen freezes, and I can't continue.

Do you know how I shoul proceed?

Thanks in advance!

Best,
Pedro Martins

**Comment by nthomasCUBE** [comment]
Hi Pedro,

good point!
seems like package:base has masked the 'print' method that I use.
I understand that i would have to add the namespace to print that I use in
the files.
Either you remove the prints or add a namespace.
I will try to add an update weekend if I find time
I quess this was due to a later update of the d3heatmap package, probably
would also work not to add 'library(d3heatmap)

best,
t


Attache Paket: ‘d3heatmap’

Die folgenden Objekte sind maskiert von ‘package:base’:

    print, save

Fehler in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘print’ for signature
‘"character"’



Am Mo., 20. Sept. 2021 um 21:47 Uhr schrieb pedro-mmartins <
***@***.***>:

**Comment by nthomasCUBE** [comment]
(..) have added namespace "base::" to print,
as consequence of the masking of method print from d3heatmap,

thanks!
